apiVersion: v1
kind: Service
metadata:
  labels:
    app: magic-frame-db
  name: magic-frame-db
  namespace: magic-frame
spec:
  type: ClusterIP
  ports:
    - name: db-port
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: magic-frame-db