apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: magic-frame-caddy
  name: magic-frame-caddy
  namespace: magic-frame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magic-frame-caddy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: magic-frame-caddy
    spec:
      containers:
        - image: magic-frame-caddy
          name: magic-frame-caddy
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
            - containerPort: 443
              protocol: UDP
            - containerPort: 2019
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/caddy
              name: magic-frame-caddy-config-pvc
            - mountPath: /data
              name: magic-frame-caddy-data-pvc
            - mountPath: /config
              name: magic-frame-caddy-config-pvc
      restartPolicy: Always
      volumes:
        - name: magic-frame-caddy-config-pvc
          persistentVolumeClaim:
            claimName: magic-frame-caddy-config-pvc
        - name: magic-frame-caddy-data-pvc
          persistentVolumeClaim:
            claimName: magic-frame-caddy-data-pvc
        - name: magic-frame-caddy-conf-pvc
          persistentVolumeClaim:
            claimName: magic-frame-caddy-conf-pvc

