apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: magic-frame-caddy-data-pvc
  namespace: magic-frame
spec:
  storageClassName: magic-frame-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
