apiVersion: v1
kind: PersistentVolume
metadata:
  name: magic-frame-caddy-conf-pv
  namespace: magic-frame
spec:
  claimRef:
    namespace: magic-frame
    name: magic-frame-caddy-conf-pvc
  storageClassName: magic-frame-storage
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/rancher/k3s/storage/magic-frame-caddy-conf-pv
    type: DirectoryOrCreate